# https://yunohost.org/en/packaging_manifest
packaging_format = 2

id = "django-bom"
name = "Django-Bom"
icon_path = "conf/icon.png",
description.en = "Django-Bom is a Django-based Bill of Materials management system."
description.fr = "Django-Bom est un système de gestion de nomenclature basé sur Django."

version = "0.1.0~ynh4"

maintainers = ["Matteo Lucas"]

[upstream]
license = "GPL-3.0-or-later"
code = "https://github.com/mpkasp/django-bom"

[integration]
yunohost = ">=11.2"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "100M"
ram.build = "100M"
ram.runtime = "100M"

[install]

  [install.domain]
  type = "domain"

  [install.sso_main_domain]
  ask.en = "Quel est le domaine principal pour la connexion SSO ?"
  type = "domain"

  [install.admin]
  type = "user"

  [install.init_main_permission]
  type = "group"
  default = "admins"

  [install.default_from_email]
  ask.en = "Default email address for various automated emails."
  type = "email"
  example = "admin@example.com"

  [install.admin_email]
  ask.en = "Email address for error reports."
  type = "email"
  example = "admin@example.com"

  [install.fixer_api_key]
  ask.en = "Fixer.io API key (used for currency conversion)"
  type = "string"
  example = "YourFixerAPIKeyHere"

  [install.debug_enabled]
  ask.en = "Should debugging be enabled? (Not recommended for production!)"
  type = "boolean"
  default = false

  [install.log_level]
  ask.en = "Logging level"
  type = "select"
  choices = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
  default = "WARNING"

[resources]

  [resources.system_user]

  [resources.install_dir]
  group = "www-data:r-x"

  [resources.data_dir]

  [resources.permissions]
  main.url = "/"

  [resources.ports]

  [resources.apt]
  packages = "build-essential, python3-dev, python3-pip, python3-venv, git, libpq-dev, postgresql, postgresql-contrib, checkinstall, pkg-config, libssl-dev, openssl"

  [resources.database]
  type = "postgresql"
