#!/bin/bash

#=================================================
# GENERIC START
#=================================================
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --app=$app --message="Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup --src_path="$install_dir"
ynh_backup --src_path="$data_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP THE PostgreSQL DATABASE
#=================================================

ynh_backup_db --db_name="$db_name"

#=================================================
# BACKUP LOGROTATE CONFIG
#=================================================

ynh_backup --src_path="/etc/logrotate.d/$app"

#=================================================
# BACKUP SYSTEMD UNIT
#=================================================

ynh_backup --src_path="/etc/systemd/system/$app.service"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --app=$app --message="Backup script completed for $app."
